import type { Market, Poll } from './types';

export const initialMarkets: Market[] = [
  {
    id: '1',
    title: 'When will APSpace app crash next?',
    description: 'Predict when the APSpace app will break or crash during registration/exam period',
    category: 'School Life',
    endDate: '2026-04-15',
    volume: 1250,
    icon: 'smartphone',
    outcomes: [
      { id: '1a', label: 'Before Week 4', probability: 65, pool: 450 },
      { id: '1b', label: 'Week 4-8', probability: 25, pool: 200 },
      { id: '1c', label: 'After Week 8', probability: 10, pool: 100 },
    ],
  },
  {
    id: '2',
    title: 'Will the lecture be nice or mad?',
    description: 'Predict the mood of tomorrow\'s surprise quiz announcement',
    category: 'Academics',
    endDate: '2026-03-26',
    volume: 890,
    icon: 'user',
    outcomes: [
      { id: '2a', label: 'Nice & Chill', probability: 35, pool: 320 },
      { id: '2b', label: 'Strict but Fair', probability: 45, pool: 410 },
      { id: '2c', label: 'Absolutely Mad', probability: 20, pool: 160 },
    ],
  },
  {
    id: '3',
    title: 'Will class end early today?',
    description: 'Predict if the professor will finish lecture before scheduled time',
    category: 'Academics',
    endDate: '2026-03-25',
    volume: 560,
    icon: 'clock',
    outcomes: [
      { id: '3a', label: 'Yes, 10+ min early', probability: 40, pool: 250 },
      { id: '3b', label: 'Yes, 5-10 min early', probability: 35, pool: 200 },
      { id: '3c', label: 'No, full duration', probability: 25, pool: 110 },
    ],
  },
  {
    id: '4',
    title: 'Cafeteria special: Will it be good?',
    description: 'Rate today\'s cafeteria surprise special meal',
    category: 'Food',
    endDate: '2026-03-25',
    volume: 420,
    icon: 'utensils',
    outcomes: [
      { id: '4a', label: 'Delicious!', probability: 15, pool: 80 },
      { id: '4b', label: 'Edible', probability: 55, pool: 280 },
      { id: '4c', label: 'Mystery Meat Alert', probability: 30, pool: 60 },
    ],
  },
  {
    id: '5',
    title: 'Will it rain during lunch break?',
    description: 'Predict the weather during the lunch break today',
    category: 'Weather',
    endDate: '2026-03-25',
    volume: 340,
    icon: 'cloud-rain',
    outcomes: [
      { id: '5a', label: 'Sunny', probability: 60, pool: 210 },
      { id: '5b', label: 'Light Rain', probability: 30, pool: 90 },
      { id: '5c', label: 'Thunderstorm', probability: 10, pool: 40 },
    ],
  },
  {
    id: '6',
    title: 'Parking spot availability?',
    description: 'Will you find a parking spot before 8:30 AM?',
    category: 'School Life',
    endDate: '2026-03-26',
    volume: 680,
    icon: 'car',
    outcomes: [
      { id: '6a', label: 'Yes, plenty', probability: 20, pool: 150 },
      { id: '6b', label: 'Yes, but far', probability: 50, pool: 350 },
      { id: '6c', label: 'No, full!', probability: 30, pool: 180 },
    ],
  },
];

export const initialPolls: Poll[] = [
  {
    id: 'p1',
    title: 'Best study spot on campus?',
    description: 'Where do you prefer to study?',
    category: 'School Life',
    createdAt: '2026-03-20',
    totalVotes: 156,
    icon: 'book-open',
    options: [
      { id: 'p1a', label: 'Library', votes: 67, color: 'blue' },
      { id: 'p1b', label: 'Cafeteria', votes: 23, color: 'green' },
      { id: 'p1c', label: 'Student Lounge', votes: 45, color: 'purple' },
      { id: 'p1d', label: 'Outside/Field', votes: 21, color: 'orange' },
    ],
  },
  {
    id: 'p2',
    title: 'Favorite cafeteria meal?',
    description: 'Which meal do you actually enjoy?',
    category: 'Food',
    createdAt: '2026-03-22',
    totalVotes: 89,
    icon: 'utensils',
    options: [
      { id: 'p2a', label: 'Nasi Lemak', votes: 42, color: 'red' },
      { id: 'p2b', label: 'Chicken Rice', votes: 31, color: 'yellow' },
      { id: 'p2c', label: 'Western Food', votes: 12, color: 'blue' },
      { id: 'p2d', label: 'None of these', votes: 4, color: 'gray' },
    ],
  },
  {
    id: 'p3',
    title: 'Best time for classes?',
    description: 'When are you most productive?',
    category: 'Academics',
    createdAt: '2026-03-23',
    totalVotes: 234,
    icon: 'clock',
    options: [
      { id: 'p3a', label: '8 AM - 10 AM', votes: 45, color: 'blue' },
      { id: 'p3b', label: '10 AM - 12 PM', votes: 89, color: 'green' },
      { id: 'p3c', label: '2 PM - 4 PM', votes: 67, color: 'yellow' },
      { id: 'p3d', label: '4 PM - 6 PM', votes: 33, color: 'red' },
    ],
  },
  {
    id: 'p4',
    title: 'How do you commute to school?',
    description: 'Share your daily commute method',
    category: 'School Life',
    createdAt: '2026-03-24',
    totalVotes: 178,
    icon: 'car',
    options: [
      { id: 'p4a', label: 'Drive', votes: 78, color: 'blue' },
      { id: 'p4b', label: 'Public Transport', votes: 56, color: 'green' },
      { id: 'p4c', label: 'Carpool/Grab', votes: 31, color: 'purple' },
      { id: 'p4d', label: 'Walk/Cycle', votes: 13, color: 'orange' },
    ],
  },
];
